# Generated by Django 5.0.1 on 2025-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherscoursesmapping',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
