# Generated by Django 5.0.1 on 2025-03-18 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacherscoursesmapping_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherscoursesmapping',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
    ]
