# Generated by Django 5.0.1 on 2025-03-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_deleted_at_teacherscoursesmapping_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacherscoursesmapping',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
