# Generated by Django 5.0.1 on 2025-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudentmapping',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
    ]
