# Generated by Django 5.0.1 on 2025-03-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coursestudentmapping_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudentmapping',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
